apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-cert-backend
    kind: SecretStore
  target:
    name: cloudflare-api-token-secret
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare-api-token
      property: cloudflare-api-token-secret
