configs:
  repositories:
    infra:
      project: default
      type: git
      url: https://github.com/m1xxos/DevOps-Projects.git
      username: argo-cd
  cm:
    accounts:
      m1xxos: "apiKey, logins"
